name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build toBuild/ --tag juphub:pipeline
    - name: Run the Docker image as container
      run: docker run -d juphub:pipeline
    - name: Push image to the Docker Hub
      run: docker image push juphub:pipeline
